export const CATEGORIES = [
  { key: "all",         label: "ALL",         icon: "🌿" },
  { key: "basics",      label: "BASICS",      icon: "🌱" },
  { key: "nutrients",   label: "NUTRIENTS",   icon: "🧪" },
  { key: "environment", label: "ENVIRONMENT", icon: "🌡" },
  { key: "growing",     label: "GROWING",     icon: "✂️" },
  { key: "harvest",     label: "HARVEST",     icon: "🌾" },
  { key: "equipment",   label: "EQUIPMENT",   icon: "💡" },
  { key: "genetics",    label: "GENETICS",    icon: "🧬" },
  { key: "problems",    label: "PROBLEMS",    icon: "🚨" },
];

export const GLOSSARY = [
  // ── BASICS ──────────────────────────────────────────────────────────────
  {
    term: "Cannabis",
    category: "basics",
    simple: "A flowering plant genus grown for its resinous buds.",
    detail: "Cannabis is a genus of flowering plants in the family Cannabaceae. It is cultivated worldwide for medicinal, recreational, and industrial uses.",
    related: ["Strain", "Indica", "Sativa"],
    quiz: {
      q: "Cannabis belongs to which plant family?",
      options: ["Cannabaceae", "Solanaceae", "Rosaceae", "Asteraceae"],
      answer: 0,
      xp: "You know cannabis belongs to the Cannabaceae family.",
    },
  },
  {
    term: "Strain",
    category: "basics",
    simple: "A named variety of cannabis with distinct traits.",
    detail: "A strain is a specific cultivar of cannabis selected for particular cannabinoid profiles, flavours, or growth characteristics. Strains are bred from Indica, Sativa, or Ruderalis genetics.",
    related: ["Genetics", "Phenotype", "Hybrid"],
    quiz: {
      q: "What defines a cannabis strain?",
      options: ["Unique genetic traits", "Pot size used", "Grow room size", "Harvest month"],
      answer: 0,
      xp: "You understand that a strain is defined by its unique genetic traits.",
    },
  },
  {
    term: "Indica",
    category: "basics",
    simple: "A cannabis subspecies known for bushy growth and relaxing effects.",
    detail: "Indica plants typically grow short and wide with broad leaves. They are associated with shorter flowering times and body-relaxing effects.",
    related: ["Sativa", "Hybrid", "Strain"],
    quiz: {
      q: "Indica plants are typically described as:",
      options: ["Short and bushy", "Tall and thin", "Vine-like", "Leafless"],
      answer: 0,
      xp: "You know Indica plants grow short and bushy.",
    },
  },
  {
    term: "Sativa",
    category: "basics",
    simple: "A cannabis subspecies with tall growth and energising effects.",
    detail: "Sativa plants grow tall with narrow leaves and longer flowering periods. They are often associated with uplifting, cerebral effects and tropical origins.",
    related: ["Indica", "Hybrid", "Landrace"],
    quiz: {
      q: "Compared to Indica, Sativa plants tend to be:",
      options: ["Taller with narrow leaves", "Shorter with wide leaves", "Identical in shape", "Thornless shrubs"],
      answer: 0,
      xp: "You know Sativa plants are taller with narrower leaves than Indica.",
    },
  },
  {
    term: "Hybrid",
    category: "basics",
    simple: "A cannabis strain bred from both Indica and Sativa genetics.",
    detail: "Hybrids are created by crossing Indica and Sativa plants to blend growth traits and effects. Most modern strains are hybrids leaning Indica-dominant or Sativa-dominant.",
    related: ["Indica", "Sativa", "Genetics"],
    quiz: {
      q: "A Hybrid strain is a cross between:",
      options: ["Indica and Sativa", "Two Indicas", "Two Sativas", "Cannabis and hemp"],
      answer: 0,
      xp: "You know a hybrid combines Indica and Sativa genetics.",
    },
  },
  {
    term: "Autoflower",
    category: "basics",
    simple: "A strain that flowers based on age, not light schedule.",
    detail: "Autoflowering strains contain Ruderalis genetics and begin flowering automatically after a set number of weeks regardless of light hours. They are faster and more compact than photoperiod strains.",
    related: ["Photoperiod", "Ruderalis", "Seedling Stage"],
    quiz: {
      q: "Autoflower plants begin flowering based on:",
      options: ["Age / time", "Light hours", "Temperature", "Pot size"],
      answer: 0,
      xp: "You know autoflowers flower based on age, not light schedule.",
    },
  },
  {
    term: "Photoperiod",
    category: "basics",
    simple: "A strain that flowers only when light hours are reduced.",
    detail: "Photoperiod strains require a change in the light schedule — typically to 12 hours of darkness — to trigger flowering. This gives growers more control over plant size before the flip.",
    related: ["Autoflower", "12/12", "The Flip"],
    quiz: {
      q: "Photoperiod plants start flowering when:",
      options: ["Dark period increases to 12h", "Nutrients are changed", "Roots fill the pot", "Temperature drops"],
      answer: 0,
      xp: "You know photoperiod plants need longer nights to flower.",
    },
  },
  {
    term: "Seed",
    category: "basics",
    simple: "The fertilised embryo of a cannabis plant used to start growth.",
    detail: "Cannabis seeds contain the genetic blueprint of the plant. They can be regular (male or female), feminised, or autoflowering, and require moisture and warmth to germinate.",
    related: ["Feminised", "Germination", "Clone"],
    quiz: {
      q: "Which seed type is guaranteed to produce female plants?",
      options: ["Feminised", "Regular", "Wild", "Hybrid"],
      answer: 0,
      xp: "You know feminised seeds are bred to produce only female plants.",
    },
  },
  {
    term: "Feminised",
    category: "basics",
    simple: "Seeds bred to produce only female plants.",
    detail: "Feminised seeds are produced by stressing a female plant to produce pollen, then using it to pollinate another female. Nearly 100% of seedlings will be female and bud-producing.",
    related: ["Seed", "Hermaphrodite", "Clone"],
    quiz: {
      q: "Feminised seeds are created using pollen from:",
      options: ["A stressed female plant", "A male plant", "A clone", "An autoflower"],
      answer: 0,
      xp: "You know feminised seeds come from female-derived pollen.",
    },
  },
  {
    term: "Germination",
    category: "basics",
    simple: "The process of a seed sprouting its first root (taproot).",
    detail: "Germination occurs when a seed absorbs moisture and warmth, cracking open to reveal the taproot. Common methods include the paper-towel technique or direct planting in moist medium.",
    related: ["Seed", "Seedling Stage", "Clone"],
    quiz: {
      q: "What is the first structure a germinating seed produces?",
      options: ["Taproot", "Cotyledons", "True leaves", "Stem"],
      answer: 0,
      xp: "You know germination produces the taproot first.",
    },
  },
  {
    term: "Clone",
    category: "basics",
    simple: "A cutting taken from a mother plant to grow a genetically identical copy.",
    detail: "Cloning involves cutting a branch from a healthy mother plant and rooting it. The resulting plant is genetically identical to the mother, preserving its traits reliably.",
    related: ["Seed", "Feminised", "Vegetative Stage"],
    quiz: {
      q: "A clone is genetically _____ to its mother plant.",
      options: ["Identical", "Different", "Feminised", "Autoflowering"],
      answer: 0,
      xp: "You know clones are genetically identical to the mother plant.",
    },
  },
  {
    term: "Vegetative Stage",
    category: "basics",
    simple: "The growth phase when the plant builds size and structure before flowering.",
    detail: "During the vegetative stage, cannabis focuses on growing stems, branches, and leaves. Plants need longer light periods (typically 18+ hours) and higher nitrogen levels to support rapid growth.",
    related: ["Flowering Stage", "Seedling Stage", "18/6"],
    quiz: {
      q: "What is the primary focus of a plant in veg?",
      options: ["Building size and structure", "Producing buds", "Making seeds", "Dying back"],
      answer: 0,
      xp: "You know the vegetative stage is about building plant structure.",
    },
  },
  {
    term: "Flowering Stage",
    category: "basics",
    simple: "The phase when cannabis develops buds containing cannabinoids.",
    detail: "The flowering stage is triggered by longer dark periods (12+ hours). Plants shift energy to producing buds, requiring higher phosphorus and potassium and lower nitrogen.",
    related: ["Vegetative Stage", "12/12", "The Flip"],
    quiz: {
      q: "What nutrient ratio shift supports the flowering stage?",
      options: ["Higher P and K, lower N", "Higher N, lower P and K", "Equal N, P, K", "No nutrients needed"],
      answer: 0,
      xp: "You know flowering needs more P and K and less N.",
    },
  },
  {
    term: "Seedling Stage",
    category: "basics",
    simple: "The earliest growth phase after germination, lasting 1–3 weeks.",
    detail: "Seedlings are fragile and require gentle light, moderate humidity, and minimal nutrients. They develop their first set of true leaves during this stage before entering veg.",
    related: ["Germination", "Vegetative Stage", "Clone"],
    quiz: {
      q: "How long does the seedling stage typically last?",
      options: ["1–3 weeks", "4–8 weeks", "8–12 weeks", "Less than 3 days"],
      answer: 0,
      xp: "You know seedlings spend roughly 1–3 weeks in the seedling stage.",
    },
  },
  {
    term: "Apical Dominance",
    category: "basics",
    simple: "The tendency of a plant's main stem to grow taller than side branches.",
    detail: "Apical dominance is driven by auxin hormones produced at the growing tip. Techniques like topping and LST disrupt this dominance to encourage bushier, multi-cola growth.",
    related: ["Topping", "LST", "SCROG"],
    quiz: {
      q: "Which technique directly breaks apical dominance?",
      options: ["Topping", "Flushing", "Decarboxylation", "Curing"],
      answer: 0,
      xp: "You know topping breaks apical dominance to encourage bushier growth.",
    },
  },

  // ── NUTRIENTS ────────────────────────────────────────────────────────────
  {
    term: "NPK",
    category: "nutrients",
    simple: "The three primary macronutrients: Nitrogen, Phosphorus, Potassium.",
    detail: "NPK ratios on nutrient labels indicate the percentage of each macronutrient. Cannabis needs different NPK ratios during veg (high N) and flower (high P/K).",
    related: ["Nitrogen", "Phosphorus", "Potassium"],
    quiz: {
      q: "What does the 'K' in NPK stand for?",
      options: ["Potassium", "Kelp", "Krypton", "Kaolinite"],
      answer: 0,
      xp: "You know K in NPK stands for Potassium.",
    },
  },
  {
    term: "Nitrogen",
    category: "nutrients",
    simple: "The primary macronutrient driving leafy vegetative growth.",
    detail: "Nitrogen (N) is essential for chlorophyll and protein synthesis. It is needed in high quantities during veg and tapered off during flowering to avoid excess that reduces bud quality.",
    related: ["NPK", "Nutrient Burn", "Vegetative Stage"],
    quiz: {
      q: "Nitrogen is most critical during which stage?",
      options: ["Vegetative", "Late flower", "Drying", "Germination"],
      answer: 0,
      xp: "You know nitrogen is most important during the vegetative stage.",
    },
  },
  {
    term: "Phosphorus",
    category: "nutrients",
    simple: "A macronutrient crucial for root development and bud production.",
    detail: "Phosphorus (P) supports root growth, energy transfer (ATP), and flowering. Demand spikes during the flowering stage, which is why PK boosters are used mid-flower.",
    related: ["NPK", "PK Booster", "Flowering Stage"],
    quiz: {
      q: "Phosphorus demand peaks during which growth phase?",
      options: ["Flowering", "Seedling", "Vegetative", "Cloning"],
      answer: 0,
      xp: "You know phosphorus is especially important during flowering.",
    },
  },
  {
    term: "Potassium",
    category: "nutrients",
    simple: "A macronutrient that regulates water uptake and bud density.",
    detail: "Potassium (K) is vital for stomatal regulation, enzyme activation, and carbohydrate transport. High K during flowering supports dense, resinous buds and overall plant health.",
    related: ["NPK", "PK Booster", "EC"],
    quiz: {
      q: "Potassium mainly helps the plant with:",
      options: ["Water uptake and bud density", "Leaf colour only", "Root rot prevention", "Seed production"],
      answer: 0,
      xp: "You know potassium regulates water uptake and supports bud density.",
    },
  },
  {
    term: "CalMag",
    category: "nutrients",
    simple: "A calcium and magnesium supplement often needed in coco or RO water.",
    detail: "CalMag supplements provide calcium and magnesium, which are secondary macronutrients. Coco coir and reverse-osmosis water are notoriously low in both, making CalMag a near-essential additive.",
    related: ["Calcium Deficiency", "Magnesium Deficiency", "Coco"],
    quiz: {
      q: "CalMag is especially important when growing in:",
      options: ["Coco coir", "Amended soil", "Rockwool only", "Fabric pots"],
      answer: 0,
      xp: "You know CalMag is especially important for coco grows.",
    },
  },
  {
    term: "EC",
    category: "nutrients",
    simple: "Electrical Conductivity — a measure of nutrient concentration in solution.",
    detail: "EC (measured in mS/cm or EC units) tells you how many dissolved salts are in your feed water. Higher EC means a stronger nutrient solution; monitoring it prevents overfeeding or underfeeding.",
    related: ["PPM", "Nutrient Burn", "Runoff"],
    quiz: {
      q: "What does a high EC reading in your feed indicate?",
      options: ["Strong nutrient solution", "Pure water", "Low pH", "High humidity"],
      answer: 0,
      xp: "You know a high EC reading means a strong nutrient solution.",
    },
  },
  {
    term: "pH",
    category: "nutrients",
    simple: "A scale measuring acidity or alkalinity of water or growing medium.",
    detail: "The pH scale runs from 0–14; 7 is neutral. Cannabis absorbs nutrients optimally at pH 6.0–7.0 in soil and 5.5–6.5 in hydro/coco. Incorrect pH causes nutrient lockout.",
    related: ["pH Lockout", "EC", "Runoff"],
    quiz: {
      q: "Optimal pH for soil cannabis is approximately:",
      options: ["6.0–7.0", "4.0–5.0", "7.5–8.5", "3.0–4.0"],
      answer: 0,
      xp: "You know soil pH should be kept between 6.0 and 7.0.",
    },
  },
  {
    term: "pH Lockout",
    category: "nutrients",
    simple: "When incorrect pH prevents roots from absorbing nutrients.",
    detail: "pH lockout occurs when root-zone pH drifts outside the optimal range, binding nutrients in forms the plant cannot absorb. Symptoms mimic deficiencies even when nutrients are present.",
    related: ["pH", "Nutrient Deficiency", "Flushing"],
    quiz: {
      q: "pH lockout symptoms often look like:",
      options: ["Nutrient deficiencies", "Overwatering", "Light burn", "Heat stress"],
      answer: 0,
      xp: "You know pH lockout mimics nutrient deficiency symptoms.",
    },
  },
  {
    term: "Nutrient Burn",
    category: "nutrients",
    simple: "Leaf tip yellowing or browning caused by excess nutrients.",
    detail: "Nutrient burn happens when EC is too high, causing salt buildup that dehydrates root cells. Early signs are crispy brown leaf tips; severe cases cause widespread yellowing and leaf curl.",
    related: ["EC", "Flushing", "Runoff"],
    quiz: {
      q: "Nutrient burn first appears as:",
      options: ["Brown/yellow leaf tips", "Purple stems", "Drooping seedlings", "White powdery spots"],
      answer: 0,
      xp: "You know nutrient burn first shows as brown or yellow leaf tips.",
    },
  },
  {
    term: "Flushing",
    category: "nutrients",
    simple: "Watering with plain pH-adjusted water to clear salt buildup from the medium.",
    detail: "Flushing is used to clear excess nutrient salts from the root zone, either as a corrective measure or in the final weeks before harvest. It involves running large volumes of plain water through the medium.",
    related: ["Runoff", "Nutrient Burn", "pH Lockout"],
    quiz: {
      q: "Why do growers flush plants before harvest?",
      options: ["To clear nutrient salts", "To increase THC", "To lower EC permanently", "To trigger flowering"],
      answer: 0,
      xp: "You know flushing clears nutrient salts before harvest.",
    },
  },
  {
    term: "Runoff",
    category: "nutrients",
    simple: "Water that drains out the bottom of a pot after watering.",
    detail: "Runoff is collected and measured for EC and pH to gauge the nutrient status of the root zone. High runoff EC indicates salt buildup; low EC may mean the plant is hungry.",
    related: ["EC", "pH", "Flushing"],
    quiz: {
      q: "What does measuring runoff EC tell you?",
      options: ["Salt buildup in the root zone", "Light intensity needed", "Harvest readiness", "Clone success rate"],
      answer: 0,
      xp: "You know runoff EC reveals salt levels in the root zone.",
    },
  },
  {
    term: "PPM",
    category: "nutrients",
    simple: "Parts Per Million — an alternative unit for measuring nutrient concentration.",
    detail: "PPM measures dissolved solids in water and is directly related to EC. Different conversion factors (500 or 700 scale) are used depending on the meter, so consistency within a grow matters most.",
    related: ["EC", "Nutrient Burn", "Runoff"],
    quiz: {
      q: "PPM and EC both measure:",
      options: ["Nutrient concentration in water", "Light intensity", "Air humidity", "Root temperature"],
      answer: 0,
      xp: "You know PPM and EC both measure nutrient concentration.",
    },
  },
  {
    term: "Mycorrhizae",
    category: "nutrients",
    simple: "Beneficial fungi that colonise roots to enhance nutrient and water uptake.",
    detail: "Mycorrhizal fungi form a symbiotic relationship with cannabis roots, extending their effective surface area. They improve phosphorus uptake, drought resistance, and overall plant health.",
    related: ["Soil", "Phosphorus", "Medium"],
    quiz: {
      q: "Mycorrhizae benefit cannabis roots by:",
      options: ["Extending root surface area", "Producing nitrogen", "Killing pests", "Raising pH"],
      answer: 0,
      xp: "You know mycorrhizae extend root surface area to boost uptake.",
    },
  },
  {
    term: "PK Booster",
    category: "nutrients",
    simple: "A high-phosphorus and high-potassium supplement used during mid-flower.",
    detail: "PK boosters are applied during peak flowering (typically weeks 4–6) to support rapid bud development and resin production. They are used temporarily and then reduced before the flush.",
    related: ["Phosphorus", "Potassium", "Flowering Stage"],
    quiz: {
      q: "When is a PK booster typically applied?",
      options: ["Mid-flower weeks 4–6", "Early veg", "Seedling stage", "After harvest"],
      answer: 0,
      xp: "You know PK boosters are used during mid-flower for bud development.",
    },
  },

  // ── ENVIRONMENT ──────────────────────────────────────────────────────────
  {
    term: "VPD",
    category: "environment",
    simple: "Vapour Pressure Deficit — the difference between air moisture capacity and actual moisture.",
    detail: "VPD combines temperature and humidity to indicate how hard a plant must work to transpire. Optimal VPD (0.8–1.5 kPa) drives nutrient uptake; too high causes stress, too low invites disease.",
    related: ["Humidity", "Temperature", "PPFD"],
    quiz: {
      q: "VPD is calculated from which two environmental factors?",
      options: ["Temperature and humidity", "CO2 and light", "pH and EC", "Fan speed and airflow"],
      answer: 0,
      xp: "You know VPD is determined by temperature and humidity together.",
    },
  },
  {
    term: "Humidity",
    category: "environment",
    simple: "The percentage of water vapour in the air (Relative Humidity, RH).",
    detail: "Cannabis needs different RH levels at each stage: ~70% for seedlings, 50–60% in veg, 40–50% in flower, and below 50% (ideally 45%) at harvest to prevent bud rot.",
    related: ["VPD", "Bud Rot", "Hygrometer"],
    quiz: {
      q: "What humidity range is safest during late flowering?",
      options: ["40–50% RH", "70–80% RH", "20–30% RH", "60–70% RH"],
      answer: 0,
      xp: "You know late-flower humidity should be kept at 40–50% RH.",
    },
  },
  {
    term: "Temperature",
    category: "environment",
    simple: "Air temperature in the grow space, ideally 20–28°C during lights-on.",
    detail: "Cannabis grows best at 20–28°C with lights on and 4–6°C cooler at night. Temperatures above 30°C reduce potency and invite pests; below 15°C slows growth significantly.",
    related: ["VPD", "Heat Stress", "CO2"],
    quiz: {
      q: "Ideal lights-on temperature range for cannabis is:",
      options: ["20–28°C", "10–15°C", "30–35°C", "35–40°C"],
      answer: 0,
      xp: "You know the ideal grow temperature is 20–28°C during lights-on.",
    },
  },
  {
    term: "CO2",
    category: "environment",
    simple: "Carbon dioxide gas that plants use for photosynthesis.",
    detail: "Ambient CO2 is ~400 ppm. Supplementing to 1000–1500 ppm can boost plant growth and yield by 20–40%, but only benefits plants that are already receiving optimal light, temperature, and nutrients.",
    related: ["PPFD", "Temperature", "DLI"],
    quiz: {
      q: "At what CO2 level do growers typically supplement?",
      options: ["1000–1500 ppm", "200–300 ppm", "5000+ ppm", "400 ppm (ambient)"],
      answer: 0,
      xp: "You know CO2 supplementation targets 1000–1500 ppm.",
    },
  },
  {
    term: "Light Schedule",
    category: "environment",
    simple: "The daily on/off cycle of grow lights controlling plant growth stages.",
    detail: "Light schedules dictate whether photoperiod plants stay in veg or trigger flowering. Common schedules are 18/6 for veg and 12/12 for flower; autoflowers can run 18/6 or 20/4 throughout.",
    related: ["18/6", "12/12", "The Flip"],
    quiz: {
      q: "Which light schedule keeps photoperiod plants in veg?",
      options: ["18/6", "12/12", "6/18", "24/0"],
      answer: 0,
      xp: "You know 18/6 is the standard schedule for keeping plants in veg.",
    },
  },
  {
    term: "18/6",
    category: "environment",
    simple: "18 hours of light and 6 hours of darkness — standard vegetative schedule.",
    detail: "The 18/6 schedule provides enough light for fast vegetative growth while giving the plant a short dark period for respiration. Some growers use 20/4 or even 24/0, though the rest period benefits plant health.",
    related: ["Light Schedule", "12/12", "Vegetative Stage"],
    quiz: {
      q: "In an 18/6 schedule, how many hours of darkness does the plant receive?",
      options: ["6 hours", "12 hours", "18 hours", "0 hours"],
      answer: 0,
      xp: "You know 18/6 means 6 hours of darkness per day.",
    },
  },
  {
    term: "12/12",
    category: "environment",
    simple: "12 hours light and 12 hours darkness — triggers flowering in photoperiod strains.",
    detail: "Switching to 12/12 tells photoperiod plants that autumn is approaching, initiating bud development. Strict light-tight dark periods are critical; any light leaks can cause hermaphroditism.",
    related: ["Light Schedule", "18/6", "The Flip"],
    quiz: {
      q: "Why must the 12-hour dark period be uninterrupted?",
      options: ["Light leaks can cause hermaphroditism", "It reduces yield anyway", "Light is not needed", "To lower temperature"],
      answer: 0,
      xp: "You know uninterrupted darkness prevents hermaphroditism.",
    },
  },
  {
    term: "The Flip",
    category: "environment",
    simple: "The moment a grower switches the light schedule from 18/6 to 12/12.",
    detail: "The flip marks the transition from vegetative to flowering stage. Plants typically double in size (the stretch) in the 2–3 weeks after the flip, so height management is important before switching.",
    related: ["12/12", "Photoperiod", "Stretch"],
    quiz: {
      q: "What physical change commonly follows The Flip?",
      options: ["The stretch (rapid height increase)", "Immediate bud formation", "Leaf drop", "Root expansion only"],
      answer: 0,
      xp: "You know plants stretch rapidly in the weeks after The Flip.",
    },
  },
  {
    term: "DLI",
    category: "environment",
    simple: "Daily Light Integral — total amount of light delivered to a plant per day.",
    detail: "DLI (mol/m²/day) is calculated from PPFD multiplied by the number of light-on seconds, divided by one million. Cannabis in flower benefits from a DLI of 40–65 mol/m²/day.",
    related: ["PPFD", "CO2", "LED"],
    quiz: {
      q: "DLI is calculated from PPFD and which other factor?",
      options: ["Duration of light per day", "Temperature", "Humidity", "CO2 level"],
      answer: 0,
      xp: "You know DLI combines PPFD with daily light duration.",
    },
  },
  {
    term: "PPFD",
    category: "environment",
    simple: "Photosynthetic Photon Flux Density — light intensity at the canopy surface.",
    detail: "PPFD (µmol/m²/s) measures how many photons useful for photosynthesis hit a square metre each second. Cannabis in flower typically needs 600–1000+ µmol/m²/s for high yields.",
    related: ["DLI", "LED", "CO2"],
    quiz: {
      q: "PPFD measures the intensity of:",
      options: ["Photons hitting the canopy", "Heat from the light", "Electrical draw of the light", "CO2 absorption rate"],
      answer: 0,
      xp: "You know PPFD measures photon intensity at the canopy.",
    },
  },
  {
    term: "Circulation Fan",
    category: "environment",
    simple: "An oscillating fan that moves air around the canopy to strengthen stems.",
    detail: "Circulation fans create a gentle breeze that strengthens stems through thigmomorphogenesis and reduces hotspots, humidity pockets, and pest habitats. They differ from extraction fans which remove air from the tent.",
    related: ["Extraction Fan", "Humidity", "Windburn"],
    quiz: {
      q: "What plant benefit does a circulation fan provide?",
      options: ["Strengthens stems via air movement", "Removes odour", "Adds CO2", "Lowers temperature only"],
      answer: 0,
      xp: "You know circulation fans strengthen stems and prevent humidity pockets.",
    },
  },

  // ── GROWING ──────────────────────────────────────────────────────────────
  {
    term: "Medium",
    category: "growing",
    simple: "The substrate in which cannabis roots grow.",
    detail: "The growing medium anchors roots and delivers water, oxygen, and nutrients. Common media include soil, coco coir, and hydroponics; each has different watering frequencies and nutrient requirements.",
    related: ["Soil", "Coco", "Hydroponics"],
    quiz: {
      q: "Which of these is NOT a common cannabis growing medium?",
      options: ["Sand alone", "Soil", "Coco coir", "Hydroponics"],
      answer: 0,
      xp: "You know the three main cannabis media are soil, coco, and hydro.",
    },
  },
  {
    term: "Soil",
    category: "growing",
    simple: "Organic growing medium that provides nutrients and beneficial microbes.",
    detail: "Soil is the most forgiving medium for beginners. It naturally buffers pH, hosts beneficial microorganisms, and can come pre-amended with nutrients, reducing the need for heavy feeding schedules.",
    related: ["Medium", "Coco", "Mycorrhizae"],
    quiz: {
      q: "One key advantage of soil over coco is:",
      options: ["Natural pH buffering", "Faster growth speed", "No watering needed", "Better for hydro pumps"],
      answer: 0,
      xp: "You know soil naturally buffers pH, making it more forgiving.",
    },
  },
  {
    term: "Coco",
    category: "growing",
    simple: "Coconut husk fibre used as an inert, fast-draining growing medium.",
    detail: "Coco coir is made from coconut husks and is pH-neutral and inert, meaning all nutrients must be supplied by the grower. It retains moisture while draining well, and pairs with frequent fertigation cycles.",
    related: ["Medium", "CalMag", "Hydroponics"],
    quiz: {
      q: "Coco coir is described as inert because it:",
      options: ["Contains no nutrients itself", "Cannot hold water", "Is chemically reactive", "Raises pH automatically"],
      answer: 0,
      xp: "You know coco is inert — all nutrients must be added by the grower.",
    },
  },
  {
    term: "Hydroponics",
    category: "growing",
    simple: "Growing plants with roots in nutrient-rich water instead of soil.",
    detail: "Hydroponic systems deliver nutrients directly to bare roots in water. Systems include DWC, NFT, and flood-and-drain. Plants grow faster but require precise pH and EC management.",
    related: ["Medium", "Coco", "EC"],
    quiz: {
      q: "In hydroponics, what replaces soil as the nutrient source?",
      options: ["Nutrient-rich water solution", "Compressed air only", "Organic compost", "Perlite alone"],
      answer: 0,
      xp: "You know hydroponics feeds roots via nutrient-rich water.",
    },
  },
  {
    term: "Perlite",
    category: "growing",
    simple: "Volcanic glass added to soil or coco to improve aeration and drainage.",
    detail: "Perlite is a lightweight, sterile volcanic rock that creates air pockets in growing media, improving oxygen availability at the roots and preventing compaction and overwatering.",
    related: ["Medium", "Soil", "Overwatering"],
    quiz: {
      q: "Perlite is added to growing media primarily to:",
      options: ["Improve aeration and drainage", "Add nutrients", "Lower pH", "Retain moisture only"],
      answer: 0,
      xp: "You know perlite improves aeration and drainage in the root zone.",
    },
  },
  {
    term: "LST",
    category: "growing",
    simple: "Low Stress Training — bending and tying branches to create an even canopy.",
    detail: "LST involves gently bending branches horizontally and securing them with ties or soft wire. This exposes lower bud sites to light, increases yields, and manages height without cutting the plant.",
    related: ["Topping", "SCROG", "Apical Dominance"],
    quiz: {
      q: "LST improves yields by:",
      options: ["Exposing lower sites to light", "Adding nutrients to roots", "Increasing humidity", "Shortening flowering time"],
      answer: 0,
      xp: "You know LST exposes lower bud sites to light to increase yield.",
    },
  },
  {
    term: "Topping",
    category: "growing",
    simple: "Cutting the main growing tip to create two new main colas.",
    detail: "Topping removes the apical meristem, which breaks apical dominance and forces two new main shoots. Repeated topping creates a bushy plant with multiple equal-sized colas for higher yields.",
    related: ["Apical Dominance", "FIM", "LST"],
    quiz: {
      q: "What is the direct result of topping a cannabis plant?",
      options: ["Two new main shoots form", "Flowering is triggered", "Roots grow faster", "Leaves are removed"],
      answer: 0,
      xp: "You know topping creates two new main shoots from one.",
    },
  },
  {
    term: "SCROG",
    category: "growing",
    simple: "Screen of Green — a net used to train plants into an even, flat canopy.",
    detail: "SCROG involves weaving branches through a horizontal screen to create a flat canopy that maximises light penetration to all bud sites. It combines well with topping and LST for maximising yield per watt.",
    related: ["LST", "Topping", "Defoliation"],
    quiz: {
      q: "What does SCROG stand for?",
      options: ["Screen of Green", "Single Crop of Growth", "Stretch Control of Growth", "Super Canopy of Green"],
      answer: 0,
      xp: "You know SCROG stands for Screen of Green.",
    },
  },
  {
    term: "Defoliation",
    category: "growing",
    simple: "Removing fan leaves to improve light and airflow to lower bud sites.",
    detail: "Strategic defoliation during veg and early flower removes large fan leaves blocking light and airflow. Done correctly it increases yield; overdoing it stresses the plant and reduces photosynthesis.",
    related: ["Lollipopping", "SCROG", "LST"],
    quiz: {
      q: "The main purpose of defoliation is to:",
      options: ["Improve light and airflow to bud sites", "Increase leaf count", "Trigger autoflowering", "Lower EC"],
      answer: 0,
      xp: "You know defoliation improves light and airflow to bud sites.",
    },
  },
  {
    term: "Lollipopping",
    category: "growing",
    simple: "Removing all growth from the lower third of the plant to focus energy on top colas.",
    detail: "Lollipopping strips the lower branches and bud sites that receive little light, redirecting the plant's energy to the top canopy. The result is fewer but larger, denser colas.",
    related: ["Defoliation", "SCROG", "Cola"],
    quiz: {
      q: "Lollipopping removes growth from the plant's:",
      options: ["Lower third", "Top third", "Middle only", "Entire canopy"],
      answer: 0,
      xp: "You know lollipopping clears the lower third of the plant.",
    },
  },
  {
    term: "Transplanting",
    category: "growing",
    simple: "Moving a plant from a smaller container to a larger one as roots expand.",
    detail: "Transplanting into progressively larger pots gives roots room to grow without being waterlogged in oversized containers. Signs it's time include roots circling the bottom or growing out of drainage holes.",
    related: ["Medium", "Fabric Pots", "Vegetative Stage"],
    quiz: {
      q: "The main reason to transplant to a larger pot is:",
      options: ["To give roots more room to grow", "To lower pH", "To trigger flowering", "To remove pests"],
      answer: 0,
      xp: "You know transplanting gives expanding roots more room to grow.",
    },
  },
  {
    term: "Watering",
    category: "growing",
    simple: "Applying water to the growing medium to hydrate the plant and roots.",
    detail: "Correct watering technique is critical: water thoroughly until runoff appears, then allow the medium to partially dry before the next watering. The lift test (checking pot weight) helps determine when to water.",
    related: ["Overwatering", "Runoff", "Medium"],
    quiz: {
      q: "The 'lift test' for watering checks the:",
      options: ["Weight of the pot", "Colour of leaves", "EC of runoff", "Root length"],
      answer: 0,
      xp: "You know the lift test checks pot weight to gauge watering time.",
    },
  },
  {
    term: "FIM",
    category: "growing",
    simple: "A topping variant that pinches the new growth tip, producing 3–4 new shoots.",
    detail: "FIM (F*** I Missed) is performed by pinching or cutting about 75% of the new shoot tip instead of removing it entirely. It produces 3–4 new growing tips instead of the 2 from a standard top.",
    related: ["Topping", "Apical Dominance", "LST"],
    quiz: {
      q: "FIM typically produces how many new shoots?",
      options: ["3–4", "1", "2", "5–6"],
      answer: 0,
      xp: "You know FIM creates 3–4 new growing tips.",
    },
  },
  {
    term: "Super Cropping",
    category: "growing",
    simple: "High-stress training that crushes and bends stems to boost resin production.",
    detail: "Super cropping involves pinching and bending a stem until the inner fibres break but the outer skin stays intact. The plant repairs the damaged area with a 'knuckle' and responds by increasing cannabinoid production.",
    related: ["LST", "Topping", "Apical Dominance"],
    quiz: {
      q: "What unique feature forms at a super-cropped stem?",
      options: ["A healing knuckle", "A new root", "A bud site", "A brown callus leaf"],
      answer: 0,
      xp: "You know super cropping creates a healing knuckle at the bend.",
    },
  },
  {
    term: "SOG",
    category: "growing",
    simple: "Sea of Green — packing many small plants together to flower early.",
    detail: "SOG uses many small, lightly trained plants flipped to flower while still small. The dense canopy maximises light use and shortens overall cycle time compared to running fewer large plants.",
    related: ["SCROG", "LST", "Clone"],
    quiz: {
      q: "SOG maximises yield by using:",
      options: ["Many small plants flipped early", "One large trained plant", "Deep water culture only", "Autoflowers exclusively"],
      answer: 0,
      xp: "You know SOG packs many small plants to maximise canopy efficiency.",
    },
  },
  {
    term: "Fabric Pots",
    category: "growing",
    simple: "Breathable fabric containers that air-prune roots for healthier growth.",
    detail: "Fabric pots allow air to penetrate the walls, causing root tips to air-prune when they reach the edge rather than circling the pot. This produces a more fibrous root system and prevents root-bound issues.",
    related: ["Transplanting", "Overwatering", "Medium"],
    quiz: {
      q: "Fabric pots prevent root circling through:",
      options: ["Air pruning at the pot walls", "Chemical treatment", "A drainage mesh inside", "Rigid plastic barriers"],
      answer: 0,
      xp: "You know fabric pots air-prune roots to prevent root-bound issues.",
    },
  },

  // ── HARVEST ──────────────────────────────────────────────────────────────
  {
    term: "Trichomes",
    category: "harvest",
    simple: "Tiny resin glands on buds that contain THC, CBD, and terpenes.",
    detail: "Trichomes are microscopic mushroom-shaped glands covering buds and sugar leaves. Their colour — clear, cloudy, or amber — indicates ripeness and is the most reliable harvest timing indicator.",
    related: ["Harvest Window", "Loupe", "THC"],
    quiz: {
      q: "Trichome colour is used to determine:",
      options: ["Harvest readiness", "Nutrient levels", "pH balance", "Root health"],
      answer: 0,
      xp: "You know trichome colour is the key indicator of harvest readiness.",
    },
  },
  {
    term: "Harvest Window",
    category: "harvest",
    simple: "The period of peak ripeness when trichomes are at optimal maturity.",
    detail: "The harvest window is when most trichomes are cloudy with some turning amber. Harvesting early gives more cerebral effects; harvesting later with more amber produces heavier, more sedating effects.",
    related: ["Trichomes", "Loupe", "Curing"],
    quiz: {
      q: "More amber trichomes at harvest typically produce:",
      options: ["Heavier, more sedating effects", "More energetic effects", "Higher THC content", "Greener buds"],
      answer: 0,
      xp: "You know more amber trichomes produce heavier, more sedating effects.",
    },
  },
  {
    term: "Loupe",
    category: "harvest",
    simple: "A magnifying lens (30–60×) used to inspect trichomes at harvest.",
    detail: "A jeweller's loupe or digital microscope lets growers see trichome colour clearly. A 60× magnification is ideal for distinguishing clear (immature), cloudy (peak THC), and amber (degrading) trichomes.",
    related: ["Trichomes", "Harvest Window", "Bud"],
    quiz: {
      q: "What magnification is ideal for inspecting trichomes?",
      options: ["60×", "5×", "10×", "200×"],
      answer: 0,
      xp: "You know a 60× loupe is ideal for reading trichome colour.",
    },
  },
  {
    term: "Drying",
    category: "harvest",
    simple: "Slowly removing moisture from harvested buds before curing.",
    detail: "Drying is done by hanging cut branches in a dark, well-ventilated space at 15–21°C and 50–60% RH for 7–14 days. Slow drying preserves terpenes and prevents harsh smoke from retained chlorophyll.",
    related: ["Curing", "Bud", "Wet Trim"],
    quiz: {
      q: "Ideal drying conditions are dark, ventilated, and at what humidity?",
      options: ["50–60% RH", "20–30% RH", "80–90% RH", "70–80% RH"],
      answer: 0,
      xp: "You know drying should be done at 50–60% RH.",
    },
  },
  {
    term: "Curing",
    category: "harvest",
    simple: "Storing dried buds in sealed jars to improve flavour and potency.",
    detail: "Curing involves placing dried buds in airtight glass jars and 'burping' them daily for the first 1–2 weeks to release moisture and gases. A 4–8 week cure dramatically improves taste, smoothness, and effect.",
    related: ["Drying", "Bud", "Terpenes"],
    quiz: {
      q: "Why do growers 'burp' jars during curing?",
      options: ["To release excess moisture and gases", "To add fresh oxygen only", "To inspect trichomes", "To lower THC content"],
      answer: 0,
      xp: "You know burping jars during curing releases moisture and gases.",
    },
  },
  {
    term: "Bud",
    category: "harvest",
    simple: "The flower of the female cannabis plant — the primary harvested product.",
    detail: "Buds form at nodes along branches and at the main cola. They are dense clusters of calyxes, pistils, and trichomes. Bud size and density depend on genetics, light intensity, and nutrition.",
    related: ["Trichomes", "Cola", "Sugar Leaves"],
    quiz: {
      q: "Cannabis buds are the plant's:",
      options: ["Flowers", "Leaves", "Roots", "Seeds only"],
      answer: 0,
      xp: "You know a cannabis bud is the flower of the female plant.",
    },
  },
  {
    term: "Cola",
    category: "harvest",
    simple: "The main central bud cluster that develops at the top of a branch.",
    detail: "The cola (from Spanish for 'tail') is the dense cluster of buds at the apex of a main stem or branch. The largest cola grows from the main stalk; topping and LST create multiple colas.",
    related: ["Bud", "Topping", "Lollipopping"],
    quiz: {
      q: "Topping a plant directly increases the number of:",
      options: ["Main colas", "Fan leaves", "Root branches", "Trichomes per bud"],
      answer: 0,
      xp: "You know topping creates more main colas on the plant.",
    },
  },
  {
    term: "Sugar Leaves",
    category: "harvest",
    simple: "Small resin-coated leaves that grow within and around buds.",
    detail: "Sugar leaves are the small, trichome-coated leaves embedded in and around buds. They are often trimmed off (wet or dry) to improve aesthetics and smoke quality but can be kept for making extracts.",
    related: ["Bud", "Wet Trim", "Dry Trim"],
    quiz: {
      q: "Sugar leaves are most valuable after harvest for:",
      options: ["Making extracts and hash", "Planting as cuttings", "Feeding the plant back", "Composting only"],
      answer: 0,
      xp: "You know sugar leaves are kept for making extracts or hash.",
    },
  },
  {
    term: "Wet Trim",
    category: "harvest",
    simple: "Trimming sugar leaves from buds immediately after cutting the plant.",
    detail: "Wet trimming is done while the plant is freshly cut and leaves are still turgid, making scissor work faster. It speeds drying but can reduce terpene preservation compared to dry trimming.",
    related: ["Dry Trim", "Sugar Leaves", "Drying"],
    quiz: {
      q: "Wet trimming is done:",
      options: ["Immediately after cutting", "After 7 days of drying", "Before the flip", "During curing"],
      answer: 0,
      xp: "You know wet trimming happens immediately after cutting the plant.",
    },
  },
  {
    term: "Dry Trim",
    category: "harvest",
    simple: "Trimming sugar leaves after the buds have fully dried.",
    detail: "Dry trimming leaves sugar leaves on buds during drying, which slows the drying process and is thought to preserve more terpenes. It is harder work as dried leaves are brittle and sticky.",
    related: ["Wet Trim", "Drying", "Curing"],
    quiz: {
      q: "Compared to wet trim, dry trim is thought to:",
      options: ["Preserve more terpenes", "Speed up drying", "Increase bud weight", "Remove more trichomes"],
      answer: 0,
      xp: "You know dry trimming is preferred for preserving terpenes.",
    },
  },
  {
    term: "Yield",
    category: "harvest",
    simple: "The total dry weight of buds harvested from a grow.",
    detail: "Yield is influenced by genetics, light intensity, canopy management, nutrient quality, and grow environment. It is measured in grams per plant or grams per watt of light used.",
    related: ["PPFD", "DLI", "SCROG"],
    quiz: {
      q: "Which factor most directly affects potential yield?",
      options: ["Light intensity (PPFD/DLI)", "Pot colour", "Seed packaging", "Timer brand"],
      answer: 0,
      xp: "You know light intensity is the biggest driver of potential yield.",
    },
  },
  {
    term: "Decarboxylation",
    category: "harvest",
    simple: "Heating cannabis to convert non-psychoactive THCA into active THC.",
    detail: "THCA in raw cannabis is non-psychoactive. Decarboxylation (decarbing) — heating to ~105–115°C for 30–45 minutes — removes the carboxyl group, converting THCA to THC and activating the plant's psychoactive compounds.",
    related: ["THC", "Trichomes", "Bud"],
    quiz: {
      q: "Decarboxylation converts THCA into:",
      options: ["Active THC", "CBD", "CBN", "Terpenes"],
      answer: 0,
      xp: "You know decarboxylation converts THCA into active THC.",
    },
  },

  // ── EQUIPMENT ────────────────────────────────────────────────────────────
  {
    term: "LED",
    category: "equipment",
    simple: "Light Emitting Diode grow light — efficient full-spectrum lighting for cannabis.",
    detail: "Modern LED fixtures use quantum board or COB diodes to deliver full-spectrum light at high efficiency. They produce less heat per watt than HPS, lower electricity costs, and are the current gold standard for indoor growing.",
    related: ["HPS", "PPFD", "Quantum Board"],
    quiz: {
      q: "Compared to HPS, LED grow lights produce:",
      options: ["Less heat per watt", "More heat per watt", "Identical heat output", "Only UV light"],
      answer: 0,
      xp: "You know LED lights produce less heat per watt than HPS.",
    },
  },
  {
    term: "HPS",
    category: "equipment",
    simple: "High-Pressure Sodium — a traditional high-output grow light.",
    detail: "HPS lights produce intense yellow-orange light ideal for flowering but are less efficient and generate significant heat compared to modern LEDs. They have been the industry standard for decades and still produce excellent results.",
    related: ["LED", "CMH", "PPFD"],
    quiz: {
      q: "HPS lights produce light in which colour range?",
      options: ["Yellow-orange", "Blue-white", "Red-infrared only", "UV only"],
      answer: 0,
      xp: "You know HPS produces yellow-orange spectrum light.",
    },
  },
  {
    term: "Carbon Filter",
    category: "equipment",
    simple: "An activated carbon canister that removes odours from extracted air.",
    detail: "A carbon filter filled with activated charcoal absorbs volatile odour molecules from grow room air before it is expelled outside. It is always paired with an extraction fan and ducting.",
    related: ["Extraction Fan", "Grow Tent", "Terpenes"],
    quiz: {
      q: "A carbon filter removes odours by using:",
      options: ["Activated charcoal absorption", "HEPA filtration", "UV sterilisation", "Water washing"],
      answer: 0,
      xp: "You know carbon filters use activated charcoal to absorb odours.",
    },
  },
  {
    term: "Extraction Fan",
    category: "equipment",
    simple: "An inline fan that removes hot, humid air from the grow space.",
    detail: "The extraction fan creates negative pressure inside the tent, drawing in fresh air through passive vents and expelling stale air through a carbon filter. It is essential for temperature and humidity management.",
    related: ["Carbon Filter", "Grow Tent", "Circulation Fan"],
    quiz: {
      q: "An extraction fan creates negative pressure to:",
      options: ["Remove hot, humid air", "Pump in CO2", "Spin the plants", "Filter water"],
      answer: 0,
      xp: "You know extraction fans remove hot, humid air from the grow.",
    },
  },
  {
    term: "Grow Tent",
    category: "equipment",
    simple: "A light-proof, reflective fabric enclosure for indoor growing.",
    detail: "Grow tents have highly reflective Mylar interiors that maximise light efficiency. They contain and direct airflow, isolate the grow environment, and make light schedules controllable and precise.",
    related: ["LED", "Carbon Filter", "Extraction Fan"],
    quiz: {
      q: "The reflective interior of a grow tent is typically made from:",
      options: ["Mylar", "Aluminium foil", "White paint", "Glass panels"],
      answer: 0,
      xp: "You know grow tent interiors are lined with reflective Mylar.",
    },
  },
  {
    term: "pH Meter",
    category: "equipment",
    simple: "An electronic probe used to measure the pH of water or nutrient solution.",
    detail: "A pH meter provides precise, real-time pH readings. It must be calibrated regularly with buffer solutions and the probe kept in storage solution to maintain accuracy.",
    related: ["pH", "EC Meter", "pH Lockout"],
    quiz: {
      q: "How often should a pH meter probe be calibrated?",
      options: ["Regularly with buffer solutions", "Once at purchase only", "Never — it self-calibrates", "Monthly with plain water"],
      answer: 0,
      xp: "You know pH meters need regular calibration with buffer solutions.",
    },
  },
  {
    term: "EC Meter",
    category: "equipment",
    simple: "A probe that measures electrical conductivity of a nutrient solution.",
    detail: "EC meters measure the total dissolved salts in solution to confirm nutrient concentration. Combined with a pH meter, they are the two most essential monitoring tools for any indoor grow.",
    related: ["EC", "pH Meter", "PPM"],
    quiz: {
      q: "An EC meter is used to verify:",
      options: ["Nutrient solution strength", "Light intensity", "Air humidity", "Root temperature"],
      answer: 0,
      xp: "You know an EC meter confirms the strength of your nutrient solution.",
    },
  },
  {
    term: "Hygrometer",
    category: "equipment",
    simple: "A device that measures temperature and relative humidity in the grow space.",
    detail: "A digital hygrometer (thermo-hygrometer) gives real-time temperature and RH readings. Accurate monitoring is essential for maintaining optimal VPD and preventing mould or heat stress.",
    related: ["Humidity", "VPD", "Temperature"],
    quiz: {
      q: "A hygrometer primarily measures:",
      options: ["Humidity and temperature", "CO2 levels", "Light spectrum", "EC of the medium"],
      answer: 0,
      xp: "You know a hygrometer measures humidity and temperature.",
    },
  },
  {
    term: "CMH",
    category: "equipment",
    simple: "Ceramic Metal Halide — a full-spectrum HID light favoured for its UV output.",
    detail: "CMH (also called LEC) lights use a ceramic arc tube to produce a broader, more natural spectrum than HPS, including UV. UV light is believed to increase trichome and terpene production.",
    related: ["HPS", "LED", "Trichomes"],
    quiz: {
      q: "CMH lights are valued for their production of:",
      options: ["UV light that boosts trichomes", "Purely red spectrum", "Infrared heating", "Blue light only"],
      answer: 0,
      xp: "You know CMH lights produce UV that can boost trichome production.",
    },
  },
  {
    term: "Quantum Board",
    category: "equipment",
    simple: "An LED panel with diodes spread across a large board for even light distribution.",
    detail: "Quantum boards spread many individual LEDs across a wide panel, reducing hotspots and improving light uniformity. They run cooler and more efficiently than older COB LED designs.",
    related: ["LED", "PPFD", "DLI"],
    quiz: {
      q: "Quantum boards improve on older COB LEDs by offering:",
      options: ["More even light distribution", "Higher heat output", "Narrower spectrum", "Lower PPFD"],
      answer: 0,
      xp: "You know quantum boards provide more even light distribution.",
    },
  },
  {
    term: "Timer",
    category: "equipment",
    simple: "A programmable device that automates the on/off cycle of grow lights.",
    detail: "A reliable timer is essential for maintaining precise light schedules. Digital timers offer minute-level precision and are safer than analogue timers for the critical 12/12 dark period.",
    related: ["Light Schedule", "12/12", "18/6"],
    quiz: {
      q: "Why is a reliable timer critical during flowering?",
      options: ["Uninterrupted dark periods prevent hermaphroditism", "It saves water", "It measures EC", "It controls fan speed"],
      answer: 0,
      xp: "You know a reliable timer ensures uninterrupted dark periods in flower.",
    },
  },
  {
    term: "RO Filter",
    category: "equipment",
    simple: "Reverse Osmosis filter that removes dissolved solids from tap water.",
    detail: "RO filters strip nearly all minerals and chlorine from tap water, giving a clean 0 EC baseline for mixing precise nutrient solutions. The near-zero mineral content requires adding CalMag to most grows.",
    related: ["EC", "CalMag", "pH Meter"],
    quiz: {
      q: "RO-filtered water typically needs what additive before use?",
      options: ["CalMag", "PK Booster", "Mycorrhizae", "pH Down only"],
      answer: 0,
      xp: "You know RO water needs CalMag added due to its zero mineral content.",
    },
  },

  // ── GENETICS ─────────────────────────────────────────────────────────────
  {
    term: "Genetics",
    category: "genetics",
    simple: "The inherited DNA blueprint that determines a plant's traits.",
    detail: "A plant's genetics dictate its potential size, flowering time, cannabinoid and terpene profile, and disease resistance. Selecting quality genetics is the single most impactful decision before starting a grow.",
    related: ["Strain", "Phenotype", "Lineage"],
    quiz: {
      q: "What is the single most impactful decision before starting a grow?",
      options: ["Selecting quality genetics", "Choosing pot colour", "Buying the best timer", "Using RO water"],
      answer: 0,
      xp: "You know genetics is the most important choice before starting a grow.",
    },
  },
  {
    term: "Lineage",
    category: "genetics",
    simple: "The documented genetic ancestry of a cannabis strain.",
    detail: "A strain's lineage lists its parent strains and shows how it was bred. Understanding lineage helps predict plant behaviour, effects, and potential issues based on the parent genetics.",
    related: ["Genetics", "Strain", "Phenotype"],
    quiz: {
      q: "Knowing a strain's lineage helps growers predict its:",
      options: ["Behaviour and effects", "Exact yield in grams", "Optimal pot size", "Water pH preference"],
      answer: 0,
      xp: "You know a strain's lineage predicts its likely behaviour and effects.",
    },
  },
  {
    term: "Phenotype",
    category: "genetics",
    simple: "The physical expression of genetics influenced by the environment.",
    detail: "Two plants from the same seed pack can exhibit different phenotypes — variations in colour, structure, terpene profile, or yield. Growers hunt phenotypes to select outstanding individual expressions for cloning.",
    related: ["Genetics", "Clone", "Lineage"],
    quiz: {
      q: "Two seeds from the same packet growing differently is due to:",
      options: ["Different phenotype expression", "Wrong pH", "Identical genetics only", "Seed age"],
      answer: 0,
      xp: "You know phenotype variation causes seeds from the same pack to differ.",
    },
  },
  {
    term: "THC",
    category: "genetics",
    simple: "Tetrahydrocannabinol — the primary psychoactive cannabinoid in cannabis.",
    detail: "THC binds to CB1 receptors in the brain, producing the psychoactive effects associated with cannabis. It exists in raw plant matter as THCA and is converted to THC via decarboxylation (heat).",
    related: ["CBD", "Trichomes", "Decarboxylation"],
    quiz: {
      q: "THC is converted from THCA through:",
      options: ["Heat (decarboxylation)", "Water curing", "Cold storage", "UV light exposure"],
      answer: 0,
      xp: "You know heat converts THCA into active THC.",
    },
  },
  {
    term: "CBD",
    category: "genetics",
    simple: "Cannabidiol — a non-psychoactive cannabinoid with therapeutic properties.",
    detail: "CBD does not produce a 'high' and is studied for anti-inflammatory, anxiolytic, and anticonvulsant effects. High-CBD strains are bred specifically and are popular for medical use.",
    related: ["THC", "CBG", "CBN"],
    quiz: {
      q: "CBD is classified as non-psychoactive because it:",
      options: ["Does not produce a 'high'", "Is destroyed by heat", "Only exists in hemp", "Blocks all CB1 receptors"],
      answer: 0,
      xp: "You know CBD is non-psychoactive and does not produce a high.",
    },
  },
  {
    term: "Terpenes",
    category: "genetics",
    simple: "Aromatic compounds in cannabis that create its distinctive scents and flavours.",
    detail: "Terpenes are volatile organic compounds produced in trichomes alongside cannabinoids. They influence flavour, aroma, and contribute to the entourage effect by modulating how cannabinoids interact with the body.",
    related: ["Entourage Effect", "Myrcene", "Limonene"],
    quiz: {
      q: "Terpenes are responsible for cannabis:",
      options: ["Aroma and flavour", "THC content", "Root growth", "Light absorption"],
      answer: 0,
      xp: "You know terpenes create cannabis's aroma and flavour.",
    },
  },
  {
    term: "Entourage Effect",
    category: "genetics",
    simple: "The synergistic interaction of cannabinoids and terpenes working together.",
    detail: "The entourage effect describes how cannabinoids (THC, CBD, CBG) and terpenes interact synergistically to produce effects greater than any single compound alone. Full-spectrum products aim to preserve this synergy.",
    related: ["Terpenes", "THC", "CBD"],
    quiz: {
      q: "The entourage effect describes the synergy between:",
      options: ["Cannabinoids and terpenes", "Light and temperature", "Soil and nutrients", "EC and pH"],
      answer: 0,
      xp: "You know the entourage effect is the synergy of cannabinoids and terpenes.",
    },
  },
  {
    term: "Ruderalis",
    category: "genetics",
    simple: "A wild cannabis subspecies from harsh climates that flowers by age.",
    detail: "Cannabis ruderalis is a small, low-THC subspecies originating from Central Asia and Russia. Its autoflowering trait — triggered by age rather than light — has been bred into modern autoflowering strains.",
    related: ["Autoflower", "Indica", "Sativa"],
    quiz: {
      q: "Ruderalis is most valued by breeders for its:",
      options: ["Autoflowering genetic trait", "Very high THC", "Massive yield", "Tropical flavour profile"],
      answer: 0,
      xp: "You know ruderalis contributes the autoflowering trait to modern strains.",
    },
  },
  {
    term: "Landrace",
    category: "genetics",
    simple: "An ancient, geographically isolated cannabis strain in its original natural form.",
    detail: "Landrace strains have evolved over centuries in specific regions (e.g. Afghani, Thai, Colombian). They are genetically pure, not crossbred, and are the ancestral building blocks of most modern hybrids.",
    related: ["Genetics", "Sativa", "Lineage"],
    quiz: {
      q: "A landrace strain is characterised by being:",
      options: ["Geographically isolated and genetically pure", "A 50/50 Indica-Sativa hybrid", "An autoflowering variety", "Always high in CBD"],
      answer: 0,
      xp: "You know landrace strains are geographically isolated and genetically pure.",
    },
  },
  {
    term: "CBG",
    category: "genetics",
    simple: "Cannabigerol — the precursor cannabinoid from which THC and CBD are synthesised.",
    detail: "CBG is often called the 'mother cannabinoid' because CBGA is the acidic precursor that enzymes convert into THCA, CBDA, and CBCA. High-CBG strains are bred by harvesting earlier when CBG hasn't fully converted.",
    related: ["THC", "CBD", "CBN"],
    quiz: {
      q: "CBG is considered the 'mother cannabinoid' because:",
      options: ["It is the precursor to THC and CBD", "It is the most abundant cannabinoid", "It causes the strongest high", "It only exists in seeds"],
      answer: 0,
      xp: "You know CBG is the precursor cannabinoid that forms THC and CBD.",
    },
  },
  {
    term: "CBN",
    category: "genetics",
    simple: "Cannabinol — a mildly psychoactive cannabinoid formed as THC degrades.",
    detail: "CBN forms when THC oxidises over time through exposure to heat, light, and oxygen. Older or poorly stored cannabis is higher in CBN. It is associated with sedative properties and is studied for sleep support.",
    related: ["THC", "CBD", "CBG"],
    quiz: {
      q: "CBN is produced when THC is exposed to:",
      options: ["Heat, light, and oxygen over time", "Cold temperatures only", "High humidity", "Extra nutrients"],
      answer: 0,
      xp: "You know CBN forms as THC degrades due to heat, light, and oxygen.",
    },
  },
  {
    term: "Myrcene",
    category: "genetics",
    simple: "The most common cannabis terpene, producing earthy, musky aromas.",
    detail: "Myrcene is associated with earthy, herbal, and fruity notes and is found in hops and mangoes. High-myrcene strains are often associated with heavy, sedating body effects.",
    related: ["Terpenes", "Limonene", "Caryophyllene"],
    quiz: {
      q: "High-myrcene cannabis strains are commonly associated with:",
      options: ["Sedating body effects", "Energising cerebral effects", "Citrus flavour only", "Zero THC"],
      answer: 0,
      xp: "You know myrcene-dominant strains tend toward sedating effects.",
    },
  },
  {
    term: "Limonene",
    category: "genetics",
    simple: "A citrus terpene associated with uplifting mood effects.",
    detail: "Limonene produces strong citrus aromas (lemon, orange) and is studied for mood-elevating and anti-anxiety properties. It is the dominant terpene in many Sativa-leaning strains.",
    related: ["Terpenes", "Myrcene", "Entourage Effect"],
    quiz: {
      q: "Limonene produces which type of aroma?",
      options: ["Citrus (lemon/orange)", "Earthy/musky", "Spicy/peppery", "Floral/lavender"],
      answer: 0,
      xp: "You know limonene creates citrus aromas in cannabis.",
    },
  },
  {
    term: "Caryophyllene",
    category: "genetics",
    simple: "A spicy, peppery terpene that uniquely binds to CB2 receptors.",
    detail: "Beta-caryophyllene is found in black pepper and cloves and is the only known terpene that directly activates cannabinoid receptors (CB2). It is associated with anti-inflammatory effects and is found in many OG-type strains.",
    related: ["Terpenes", "Entourage Effect", "Myrcene"],
    quiz: {
      q: "Caryophyllene is unique among terpenes because it:",
      options: ["Directly binds to CB2 receptors", "Is the most abundant terpene", "Only exists in Indica strains", "Converts to THC when heated"],
      answer: 0,
      xp: "You know caryophyllene is the only terpene that binds to CB2 receptors.",
    },
  },

  // ── PROBLEMS ─────────────────────────────────────────────────────────────
  {
    term: "Nutrient Deficiency",
    category: "problems",
    simple: "A condition where the plant lacks sufficient levels of one or more nutrients.",
    detail: "Deficiencies show as yellowing, browning, or discolouration patterns on leaves that indicate which nutrient is lacking. They can be caused by actual low nutrient supply or pH lockout preventing absorption.",
    related: ["pH Lockout", "NPK", "CalMag"],
    quiz: {
      q: "A nutrient deficiency can be caused by low nutrients OR by:",
      options: ["pH lockout blocking absorption", "Too much light", "High CO2", "Root rot only"],
      answer: 0,
      xp: "You know pH lockout can cause deficiency symptoms despite adequate nutrients.",
    },
  },
  {
    term: "Overwatering",
    category: "problems",
    simple: "Watering too frequently, suffocating roots by depriving them of oxygen.",
    detail: "Overwatering is one of the most common beginner mistakes. Symptoms include drooping, yellowing, and limp leaves. It causes root oxygen deprivation and can quickly lead to root rot if not corrected.",
    related: ["Root Rot", "Watering", "Fabric Pots"],
    quiz: {
      q: "Overwatering primarily harms plants by depriving roots of:",
      options: ["Oxygen", "Nutrients", "Water", "Light"],
      answer: 0,
      xp: "You know overwatering deprives roots of oxygen.",
    },
  },
  {
    term: "Root Rot",
    category: "problems",
    simple: "A disease caused by anaerobic pathogens that turns roots brown and slimy.",
    detail: "Root rot is caused by Pythium and similar water-borne pathogens that thrive in waterlogged, low-oxygen conditions. Affected roots turn brown and slimy and emit a foul smell, severely impairing nutrient uptake.",
    related: ["Overwatering", "Hydroponics", "Bud Rot"],
    quiz: {
      q: "Root rot is most recognisable by roots that are:",
      options: ["Brown and slimy with a foul smell", "White and firm", "Yellow and brittle", "Purple and twisted"],
      answer: 0,
      xp: "You know root rot turns roots brown and slimy with a foul odour.",
    },
  },
  {
    term: "Bud Rot",
    category: "problems",
    simple: "Botrytis mould that grows inside dense buds in high-humidity conditions.",
    detail: "Bud rot (Botrytis cinerea) starts inside dense colas and spreads outward. It is grey-brown and musty and spreads rapidly. Prevention requires keeping RH below 50% and ensuring good airflow in flower.",
    related: ["Humidity", "Circulation Fan", "Drying"],
    quiz: {
      q: "Bud rot is best prevented by keeping RH below:",
      options: ["50%", "70%", "30%", "80%"],
      answer: 0,
      xp: "You know keeping RH below 50% is key to preventing bud rot.",
    },
  },
  {
    term: "Heat Stress",
    category: "problems",
    simple: "Plant stress caused by temperatures above 28–30°C.",
    detail: "Heat stress causes leaf curling (taco-ing), bleaching near the light, and reduced terpene and cannabinoid production. Persistent heat above 30°C slows growth, stresses roots, and invites spider mites.",
    related: ["Temperature", "Light Stress", "LED"],
    quiz: {
      q: "A common visual sign of heat stress is:",
      options: ["Leaves curling upward (taco-ing)", "Purple colouration", "Rapid flowering", "White trichomes turning amber quickly"],
      answer: 0,
      xp: "You know heat stress causes leaves to curl upward (taco-ing).",
    },
  },
  {
    term: "Hermaphrodite",
    category: "problems",
    simple: "A plant that develops both male pollen sacs and female buds.",
    detail: "Hermaphroditism is triggered by stress (heat, light leaks, damage) or unstable genetics. Hermie plants produce pollen that fertilises female buds, causing seedy harvests and greatly reduced quality.",
    related: ["Feminised", "Light Schedule", "Bud"],
    quiz: {
      q: "Hermaphroditism in cannabis is most often triggered by:",
      options: ["Environmental stress or light leaks", "Overfeeding nutrients", "Correct pH", "Low EC solution"],
      answer: 0,
      xp: "You know stress and light leaks trigger hermaphroditism.",
    },
  },
  {
    term: "Spider Mites",
    category: "problems",
    simple: "Tiny sap-sucking pests that create white stippling on leaves and webbing.",
    detail: "Spider mites (Tetranychus urticae) thrive in hot, dry conditions above 26°C. They appear as tiny dots on leaf undersides and leave white speckling on the top surface. Severe infestations form visible webbing across the canopy.",
    related: ["Heat Stress", "Thrips", "Circulation Fan"],
    quiz: {
      q: "Spider mites thrive in conditions that are:",
      options: ["Hot and dry", "Cool and humid", "Wet and dark", "High CO2 only"],
      answer: 0,
      xp: "You know spider mites thrive in hot, dry growing conditions.",
    },
  },
  {
    term: "Powdery Mildew",
    category: "problems",
    simple: "A fungal disease causing white powdery patches on leaves.",
    detail: "Powdery mildew (PM) is a fungus that spreads via airborne spores and thrives in humid, stagnant conditions with poor airflow. White powdery spots appear on leaves and buds and must be treated immediately to prevent spread.",
    related: ["Humidity", "Circulation Fan", "Bud Rot"],
    quiz: {
      q: "Powdery mildew appears on cannabis as:",
      options: ["White powdery patches on leaves", "Brown root slime", "Tiny red dots", "Yellow leaf tips"],
      answer: 0,
      xp: "You know powdery mildew shows as white powdery patches on leaves.",
    },
  },
  {
    term: "Light Stress",
    category: "problems",
    simple: "Damage caused by lights that are too close or too intense for the plant.",
    detail: "Light stress (light burn) causes bleaching, whitening, or bleached-looking leaves and buds at the top of the canopy closest to the light. It can reduce potency in affected areas and stunts growth.",
    related: ["Heat Stress", "LED", "PPFD"],
    quiz: {
      q: "Light stress most commonly affects which part of the plant?",
      options: ["The canopy tops closest to the light", "The roots", "Lower bud sites", "Fan leaves only"],
      answer: 0,
      xp: "You know light stress bleaches the canopy tops closest to the light.",
    },
  },
  {
    term: "Stretch",
    category: "problems",
    simple: "Rapid and excessive stem elongation that occurs in the first weeks of flower.",
    detail: "Post-flip stretch is normal but can become problematic in Sativa-dominant strains, doubling or tripling height. Techniques like SCROG, super cropping, and the flip timing help manage stretch before it outgrows the tent.",
    related: ["The Flip", "SCROG", "Super Cropping"],
    quiz: {
      q: "The stretch most commonly occurs during the:",
      options: ["First 2–3 weeks of flowering", "Seedling stage", "Late veg only", "Drying phase"],
      answer: 0,
      xp: "You know the stretch happens in the first 2–3 weeks of flowering.",
    },
  },
  {
    term: "Thrips",
    category: "problems",
    simple: "Small slender insects that rasp leaf surfaces, leaving silver streaks.",
    detail: "Thrips (Thysanoptera) feed by scraping leaf cells and leaving distinctive silver or bronze streaking. They can spread plant viruses and are difficult to eradicate once established; yellow sticky traps aid early detection.",
    related: ["Spider Mites", "Fungus Gnats", "Circulation Fan"],
    quiz: {
      q: "The distinctive damage pattern left by thrips is:",
      options: ["Silver or bronze streaks on leaves", "White powdery circles", "Brown tips only", "Wilted roots"],
      answer: 0,
      xp: "You know thrips leave silver or bronze streaks on leaf surfaces.",
    },
  },
  {
    term: "Fungus Gnats",
    category: "problems",
    simple: "Small flies whose larvae live in moist soil and damage roots.",
    detail: "Fungus gnat larvae (Bradysia spp.) feed on root hairs and organic matter in the top layer of soil, stunting growth. Adults are harmless but indicate overwatering. Allowing the medium to dry out between waterings is the best prevention.",
    related: ["Overwatering", "Soil", "Root Rot"],
    quiz: {
      q: "Fungus gnat larvae damage cannabis by:",
      options: ["Feeding on root hairs in the soil", "Eating leaves from above", "Spreading powdery mildew", "Laying eggs in buds"],
      answer: 0,
      xp: "You know fungus gnat larvae feed on root hairs in the growing medium.",
    },
  },
  {
    term: "Calcium Deficiency",
    category: "problems",
    simple: "A lack of calcium causing brown spots and weak stems.",
    detail: "Calcium deficiency presents as brown irregular spots on mid-to-upper leaves, weak stems, and distorted new growth. It is common in coco grows or when using RO water without CalMag supplementation.",
    related: ["CalMag", "Magnesium Deficiency", "Nutrient Deficiency"],
    quiz: {
      q: "Calcium deficiency is most likely in which growing medium?",
      options: ["Coco coir without CalMag", "Rich amended soil", "Nutrient-heavy DWC", "Peat with dolomite lime"],
      answer: 0,
      xp: "You know calcium deficiency is most common in coco without CalMag.",
    },
  },
  {
    term: "Magnesium Deficiency",
    category: "problems",
    simple: "A lack of magnesium causing yellowing between leaf veins (interveinal chlorosis).",
    detail: "Magnesium is the central atom in chlorophyll. Deficiency shows as yellowing between the veins of older/lower leaves while veins stay green. It is common in coco, RO-water grows, and at low pH.",
    related: ["CalMag", "Calcium Deficiency", "pH Lockout"],
    quiz: {
      q: "Magnesium deficiency is identified by yellowing:",
      options: ["Between the veins of older leaves", "At the leaf tips only", "On new growth first", "Along the entire leaf edge"],
      answer: 0,
      xp: "You know magnesium deficiency causes interveinal yellowing on older leaves.",
    },
  },
  {
    term: "Tip Burn",
    category: "problems",
    simple: "Brown or burnt leaf tips caused by localised calcium deficiency or excess nutrients.",
    detail: "Tip burn is the browning of leaf tip edges and is caused by inadequate calcium transport to fast-growing tips or by high EC/salt stress. It is one of the first signs of either overfeeding or a mild calcium issue.",
    related: ["Calcium Deficiency", "Nutrient Burn", "EC"],
    quiz: {
      q: "Tip burn appears first on which part of the leaf?",
      options: ["The very tips and edges", "The middle of the blade", "Along the main vein", "The underside only"],
      answer: 0,
      xp: "You know tip burn shows as browning at the leaf tips and edges.",
    },
  },
  {
    term: "Windburn",
    category: "problems",
    simple: "Leaf stress caused by excessive airflow directed directly onto foliage.",
    detail: "Windburn is caused by fans blowing too hard directly at leaves, causing them to claw downward (similar to nitrogen toxicity) or develop dry, brown edges. Oscillating fans reduce the risk.",
    related: ["Circulation Fan", "Heat Stress", "Overwatering"],
    quiz: {
      q: "Windburn causes leaves to:",
      options: ["Claw downward and develop dry edges", "Turn yellow uniformly", "Develop white spots", "Grow upward rapidly"],
      answer: 0,
      xp: "You know windburn causes leaves to claw downward with dry edges.",
    },
  },
];
